# Generated by Django 4.2.22 on 2025-06-09 05:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("min_temperature", models.FloatField()),
                ("max_temperature", models.FloatField()),
            ],
        ),
    ]
